{
    "track_id": "TSimaCnE",
    "prompt": "Unknown ERROR->ActionFailed",
    "time": "2021-12-21 07:31:40",
    "content": "Traceback (most recent call last):\n  File \"C:\\Users\\LazyO\\Desktop\\hokabot\\hoka\\.\\models\\exceptions.py\", line 104, in _track_error\n    raise exception\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\message.py\", line 155, in _run_matcher\n    await matcher.run(bot, event, state)\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\matcher.py\", line 584, in run\n    await handler(self, bot, event, self.state)\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\handler.py\", line 81, in __call__\n    await self.func(\n  File \"C:\\Users\\LazyO\\Desktop\\hokabot\\hoka\\src/plugins\\roll\\__init__.py\", line 35, in _\n    await roll.finish(start + end)\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\matcher.py\", line 519, in finish\n    await bot.send(event=event, message=message, **kwargs)\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 471, in send\n    return await self.send_msg(**params)\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 416, in call_api\n    return await super().call_api(api, **data)\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\adapters\\_base.py\", line 181, in call_api\n    raise exception\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\adapters\\_base.py\", line 164, in call_api\n    result = await self._call_api(api, **data)\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 363, in _call_api\n    return _handle_api_result(await ResultStore.fetch(\n  File \"C:\\Users\\LazyO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 192, in _handle_api_result\n    raise ActionFailed(**result)\nnonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 4}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=\u8bf7\u53c2\u8003 go-cqhttp \u7aef\u8f93\u51fa>\n"
}